src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ArticleRepository::class)]
class Article
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $content = null;

    #[ORM\Column(length: 255)]
    private ?string $cover = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $date_created = null;

    #[ORM\Column(length: 255)]
    private ?string $slug = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCover(): ?string
    {
        return $this->cover;
    }

    public function setCover(string $cover): self
    {
        $this->cover = $cover;

        return $this;
    }

    public function getDateCreated(): ?\DateTimeImmutable
    {
        return $this->date_created;
    }

    public function setDateCreated(\DateTimeImmutable $date_created): self
    {
        $this->date_created = $date_created;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(?string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }
}

src/Controller/MainController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Repository\ArticleRepository;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class MainController extends AbstractController
{
    #[Route('/', name: 'app_main')]
    public function index(ArticleRepository $repoArticle): Response
    {
        $cellules = $repoArticle->findAll();

        return $this->render('main/index.html.twig', compact("cellules"));
    }

    #[Route('/show/{slug}', name: 'app_show')]
    public function show(Article $article): Response
    {
        return $this->render('main/show.html.twig', compact("article"));
    }
}

templates/main/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Accueil{% endblock %}

{% block body %}
<div class="container col-8 mx-auto">
    <div class="card bg-dark mb-5" style="height:420px; background-image: url('{{ asset('uploads/photos/thumb-1920-546091.jpg') }}'); background-size: cover;">
        <div class="col-6 text-end text-white h-100">
            <div class="me-auto my-auto h-100 align-middle">
                {# En cours #}
            </div>


        </div>
        <div class="col-6"></div>
    </div>
    <div class="row justify-content-start my-4">
        <h2 class="textOrange mb-4">Nos Articles</h2>

        {% for data in cellules %}
            <a href="{{ path('app_show', {'slug': data.slug}) }}" class="text-decoration-none col-4 textOrange my-2">
                <div class="card">
                    <img src="{{ asset('uploads/photos/' ~ data.cover) }}" class="card-img-top"  alt="{{data.title}}">
                    <div class="card-body" style="min-height:20vh;">
                        <h3 class="h4">{{ data.title }}</h3>
                    </div>
                </div>
            </a>
        {% endfor %}
        
    </div>
</div>
{% endblock %}

templates/main/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Article{% endblock %}

{% block body %}
    <div class="container col-8 mx-auto">
        <form class="my-3">
            <input type="button" class="btn btn-orange" value="Retour" onclick="history.go(-1)">
        </form>    

        <div class="card mb-5">
            <img src="{{ asset('uploads/photos/' ~ article.cover) }}" class="card-img-top"  alt="{{article.title}}">
            <div class="card-body">
                <h3 class="my-4 text-center textOrange">{{ article.title }}</h3>
                <p>{{article.content}} </p>
            </div>
            <div class="card-footer text-muted">
                Publié le {{article.dateCreated|date(" d/m/Y à H:i")}}
            </div>
        </div>
    </div>
    



{% endblock %}